# Copyright (C) 2026  Sutou Kouhei <kou@clear-code.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

name: Test
on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
    tags:
      - "**"
  pull_request:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CCACHE_DIR: ${{ github.workspace }}/cache
      MECAB_KO_PREFIX: /usr/lib/groonga/tokenizer-mecab-ko
    steps:
      - uses: actions/checkout@v6
      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: cache
          key: test-ubuntu-ccache-${{ hashFiles('CMakeLists.txt', 'tokenizers/**') }}
          restore-keys: test-ubuntu-ccache-
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y -V \
            autoconf \
            automake \
            build-essential \
            ccache \
            cmake \
            ninja-build \
            ruby-dev
      - name: Install Groonga
        run: |
          sudo apt install -y -V ca-certificates lsb-release wget
          wget https://packages.groonga.org/ubuntu/groonga-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V \
            ./groonga-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
          sudo apt install -y -V \
            groonga \
            libgroonga-dev
      - name: CMake
        run: |
          GROONGA_CMAKE_DIR=$(dirname $(find /usr -name GroongaConfig.cmake 2>/dev/null | head -1))
          cmake -S . -B build -GNinja \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DGroonga_DIR=${GROONGA_CMAKE_DIR} \
            -DMECAB_KO_PRIVATE_PREFIX=${MECAB_KO_PREFIX}
      - name: Build
        run: |
          sudo cmake --build build
      - name: Install grntest
        run: |
          sudo gem install grntest
      - name: Test
        run: |
          BUILD_DIR="$(pwd)/build" bash test/run.sh
